Update patch set 3
Patch Set 3:

Hi, I tried it on another server and got the same error:
/home/w/extensions/Math/math# make
ocamlopt -c util.ml
ocamlc -c render_info.mli
ocamlc -c tex.mli
ocamlyacc parser.mly
9 shift/reduce conflicts.
ocamlc -c parser.mli
ocamlopt -c parser.ml
ocamlc -c html.mli
ocamlopt -c html.ml
ocamlc -c mathml.mli
ocamlopt -c mathml.ml
ocamlc -c texutil.mli
ocamlopt -c texutil.ml
File "texutil.ml", line 103, characters 0-3:
Error: Syntax error
make: *** [texutil.cmx] Fehler 2
rm parser.ml

Patch-set: 3