Update patch set 22
Patch Set 22:

I have errors with vagrant.
vagrant@mediawiki-vagrant:~/math$ php /vagrant/mediawiki/tests/phpunit/phpunit.php ./tests/MathLaTeXMLTest.php
PHPUnit 3.7.19 by Sebastian Bergmann.

Configuration read from /vagrant/mediawiki/tests/phpunit/suite.xml

FEF..

Time: 31 seconds, Memory: 25.75Mb

There was 1 error:

1) MathLaTeXMLTest::testTimeout5
PHP_Invoker_TimeoutException: Execution aborted after 10 seconds

/vagrant/mediawiki/includes/HttpFunctions.php:886
/vagrant/mediawiki/extensions/Math/MathLaTeXML.php:118
/vagrant/mediawiki/extensions/Math/tests/MathLaTeXMLTest.php:40
/vagrant/mediawiki/tests/phpunit/MediaWikiTestCase.php:116
/vagrant/mediawiki/tests/phpunit/MediaWikiPHPUnitCommand.php:64
/vagrant/mediawiki/tests/phpunit/MediaWikiPHPUnitCommand.php:48

--


There were 2 failures:

1) MathLaTeXMLTest::testMakeRequest
This test printed output:

/vagrant/mediawiki/tests/phpunit/MediaWikiTestCase.php:116
/vagrant/mediawiki/tests/phpunit/MediaWikiPHPUnitCommand.php:64
/vagrant/mediawiki/tests/phpunit/MediaWikiPHPUnitCommand.php:48

2) MathLaTeXMLTest::testTimeout1
timeout call errormessage
Failed asserting that '<strong class='error'>Failed to parse (LaTeXML Invalid response from server http://latexml.mathweb.org/convert HTTP request failed due to unknown error.): a+b</strong>
' contains "LaTeXML Timeout from ".

/vagrant/mediawiki/extensions/Math/tests/MathLaTeXMLTest.php:60
/vagrant/mediawiki/tests/phpunit/MediaWikiTestCase.php:116
/vagrant/mediawiki/tests/phpunit/MediaWikiPHPUnitCommand.php:64
/vagrant/mediawiki/tests/phpunit/MediaWikiPHPUnitCommand.php:48

FAILURES!
Tests: 5, Assertions: 10, Failures: 2, Errors: 1.

Of course these error would not occur if I'd do proper testing in mock up style and not test the actual execution of the commands.

Do these error relate to the MWHttpRequest classes?
I was very surprised that the test did not fail when they were executed by jenkins.

Patch-set: 22