Update patch set 4
Patch Set 4:

I installed sqlite now I get the a similar problem

A database query error has occurred.
Query: SELECT  notification_event  FROM unittest_echo_notification LEFT JOIN unittest_echo_event ON ((notification_event=event_id))  WHERE notification_user = '1' AND notification_bundle_base = '1' AND notification_read_timestamp IS NULL AND event_type IN ('welcome','edit-user-talk','reverted','mention','user-rights')   LIMIT 100
Function: MWDbEchoBackend::getNotificationCount
Error: 1 no such table: unittest_echo_notification

Backtrace:
#0 /vagrant/mediawiki/includes/db/Database.php(1145): DatabaseBase->reportQueryError('no such table: ...', 1, 'SELECT  notific...', 'MWDbEchoBackend...', false)
#1 /vagrant/mediawiki/includes/db/Database.php(1612): DatabaseBase->query('SELECT  notific...', 'MWDbEchoBackend...')

Patch-set: 4
Reviewer: Physikerwelt <183@e9e9afe9-4712-486d-8885-f54b72dd1951>
Label: Verified=0